#! /usr/bin/env python

import rospy

from sensor_msgs.msg import LaserScan
from geometry_msgs.msg import Twist

from Faulkner import avoidance

pub = None

def clbk_laser(msg):
    action = Twist()
    a = avoidance()

    # Update avoidance action
    a.UpdateAction(msg)
    rospy.loginfo("%s %s %f/%f", a.state_description, a.regions, a.linear_x, a.angular_z)

    # Publish action
    action.linear.x = a.linear_x
    action.angular.z = a.angular_z
    pub.publish(action)

def main():
    global pub
    
    rospy.init_node('reading_laser')
    pub = rospy.Publisher('/cmd_vel', Twist, queue_size=1)
    sub = rospy.Subscriber('scan', LaserScan, clbk_laser)
    
    rospy.spin()

if __name__ == '__main__':
    main()